### ISSUE TITLE
Wrong kafka configuration in platform templates 

### ISSUE THREAD

**Issue by ppenhouet** [punchplatform/punchbox#5]
"kafka" : {
    "clusters" : {
        "local" : {
            "brokers" : ["node01:9092", "node02:9092", "node03:9092"],

must be 

"kafka" : {
    "clusters" : {
        "local" : {
          "brokers_with_ids" : [
              {"id" : 1, "broker" : "node01:9092" },
              {"id" : 2, "broker" : "node02:9092" },
              {"id" : 3, "broker" : "node03:9092" }
          ],

**Comment by jmerdy** [comment]
Bonjour,
Je rencontre le même problème. Ceci bloque le log injector; en effet lorsque j'utilise le log injector avec une sortie kafka j'ai le message suivant : 
```
Exception in thread "main" org.thales.punch.settings.api.MissingRequiredSettingException: 'punchplatform.properties.kafka.clusters.local.brokers_with_ids' is missing.
	at org.thales.punch.settings.impl.SettingsMapImpl.get(SettingsMapImpl.java:110)
	at org.thales.punch.settings.impl.SettingsMapImpl.getAsSettingsList(SettingsMapImpl.java:253)
	at org.thales.punch.settings.impl.SettingsMapImpl.getAsRequiredSettingsList(SettingsMapImpl.java:470)
	at org.thales.punch.injector.KafkaSender.<init>(KafkaSender.java:57)
	at org.thales.punch.injector.InjectorConfig.<init>(InjectorConfig.java:205)
	at org.thales.punch.injector.Main.main(Main.java:430)
```
Pour que cela fonctionne j'ai modifier à la main mon punchplatform.properties.

Avez-vous une date de correction pour ce bug ?

**Comment by soltiz** [comment]
Bonjour,
La variante (cf doc pp.properties) de settings kafka 'brokers_with_ids" est effectivement la seule qui fonctionne. La variante 'brokers' qui est dans la conf standalone ne fonctionne pas dans certains outils'. Un bug produit existe sur le sujet, mais n'a pas été encore traité...donc il faut adapter le conf.properties effectivement.

⁣Télécharger BlueMail pour Android ​

Le 16 juil. 2020 à 17:34, à 17:34, jmerdy <notifications@github.com> a écrit:
